# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: grotto_thrvly_dev
  pool:     5
  username: root
  password: root
  template: template0

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: grotto_thrvly_test
  pool:     5
  username: root
  password: root
  template: template0

production:
  adapter:  postgresql  
  encoding: unicode
  host:     localhost
  database: grotto_thrvly_prod
  pool:     5
  username: root
  password: root
  template: template0